config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  # schedule_results page
  resource :match do
    resources :schedule_results, controller: 'match/schedule_results', except: [:show]
  end

  # contact page
  resources :contacts, only: [:index] do
    collection do
      post :confirm
      post :thanks
    end
  end

  # players page
  resources :players, except: [:show]

  devise_for :users

  # admin page
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # 準備中 page
  get 'preparation', to: 'preparation#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/match.rb
module Match
  def self.table_name_prefix
    'match_'
  end
end

app/models/schedule_result.rb
class ScheduleResult < ApplicationRecord
  belongs_to :user

  enum section: { 第1節: 0,  第2節: 1, 第3節: 2 , 第4節: 3, 第5節: 4, 第6節: 5, 第7節: 6, 第8節: 7, 第9節: 8, 第10節: 9, 第11節: 10,
                  第12節: 11, 第13節: 12, 第14節: 13, 第15節: 14, 第16節: 15, 第17節: 16, 第18節: 17, 第19節: 18, 第20節: 19, その他: 20 }, _prefix: true
  enum opponent: { 未定: 0, リューレント: 1,  サザンクロス: 2, ドラックス: 3, トライアンフ: 4, ビーバー: 5 }
  enum match_result: { 勝ち: 1,  負け: 2, 引分け: 3 }
  enum stadium: { 古々崎第1G: 0,  古々崎第2G: 1, 運動公園: 2, その他: 3 }, _prefix: true
  enum home_and_away: { ホーム: 0,  アウェー: 1 }

  #TODO: datetimeのバリデーションを設定する
  validates :section, inclusion: { in: ScheduleResult.sections.keys }
  validates :opponent, inclusion: { in: ScheduleResult.opponents.keys }
  validates :match_result, inclusion: { in: ScheduleResult.match_results.keys }, allow_blank: true
  validates :stadium, inclusion: { in: ScheduleResult.stadia.keys }
  validates :home_and_away, inclusion: { in: ScheduleResult.home_and_aways.keys }
end

app/controllers/match/schedule_results_controller.rb
class Match::ScheduleResultsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @schedule_results = ScheduleResult.all.order(section: "ASC")
  end

  def new
    if admin_user?
      @schedule_results = ScheduleResult.new
    else
      flash[:success] = '権限がないためアクセスできません'
      redirect_to match_schedule_results_path
    end
  end

  def create
    @schedule_result = ScheduleResult.create(schedule_result_params)
    @schedule_result.user_id = current_user.id
    if @schedule_result.save
      flash[:success] = '登録が完了しました'
      redirect_to match_schedule_results_path
    else
      flash[:danger] = '登録が失敗しました'
      render :new
    end
  end

  def edit
    if admin_user?
      @schedule_result = find_Schedule_Result_id
    else
      flash[:success] = '権限がないためアクセスできません'
      redirect_to match_schedule_results_path
    end
  end

  def update
    @schedule_result = find_Schedule_Result_id
    if @schedule_result.update(schedule_result_params)
    flash[:success] = '更新が完了しました'
    redirect_to match_schedule_results_path
    else
      render :edit
    end
  end

  def destroy
    schedule_result = find_Schedule_Result_id
    schedule_result.destroy
    flash[:success] = '削除が完了しました'
    redirect_to match_schedule_results_path
  end

  private
  def find_Schedule_Result_id
    ScheduleResult.find(params[:id])
  end

  def schedule_result_params
    params.require(:schedule_result).permit(:match_date_time, :section, :opponent, :match_result, :stadium, :home_and_away)
  end
end

app/helpers/match/schedule_results_helper.rb
module Match::ScheduleResultsHelper
end

app/views/match/schedule_results/_form.html.haml
%div.section-input_schedule
  %div.ml-auto.posts_button.post
    = link_to '試合日程・結果に戻る', match_schedule_results_path, title: '試合日程・結果一覧', class: 'botton'

app/views/match/schedule_results/edit.html.haml
%dev.d-flex.align-items-center
  %h1 試合スケジュール変更

= render "form"

-#NOTE: newと同様フォームだが、urlが異なるためパーシャルを使っていない
= form_with model: @schedule_result, url: match_schedule_result_path, local: true  do |f|
  %div.form-group
    = f.label :match_date_time, '試合日時'
    = f.datetime_field :match_date_time, class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※試合日時が未定の場合、選択不要です
  %div.form-group
    = f.label :section, '節'
    = f.select :section, ScheduleResult.sections.keys, class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※第何節の試合かを選択してください
  %div.form-group
    = f.label :opponent, '対戦チーム'
    = f.select :opponent, ScheduleResult.opponents.keys, class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※対戦チームを選択してください
  %div.form-group
    = f.label :match_result, '試合結果'
    = f.select :match_result, ScheduleResult.match_results.keys, include_blank: "", class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※試合結果が未定の場合、選択不要です
  %div.form-group
    = f.label :stadium, '会場'
    = f.select :stadium, ScheduleResult.stadia.keys, class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※会場を選択してください
  %div.form-group
    = f.label :home_and_away, 'ホーム&アウェー'
    = f.select :home_and_away, ScheduleResult.home_and_aways.keys,class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※ホームまたはアウェーを選択してください

  = f.submit '更新する', class: 'btn btn-info btn-block'

app/views/match/schedule_results/index.html.haml
%div.d-flex.align-items-center
  %div.lower_head
    %h3 MATCH / RESULTS
    %h1
      試合日程・結果(
      = Time.now.year
      年)
%div.section-category
  %h3 松戸市リーグ 1部 テスト

- if user_signed_in? && current_user.admin?
  %div.section-input_schedule
    %div.ml-auto.buttom.post
      %div.btn.btn-outline-info
        = link_to '試合日程を登録する', new_match_schedule_result_path, title: '試合日程・結果一覧', class: 'button'

%table.table.schedule_result
  %thead
    %tr
      %th 試合日時
      %th 節
      %th 対戦チーム
      %th 試合結果
      %th 会場
      %th ホーム or アウェー
      %th 作成日時
      %th 編集/削除
  %tbody
    - @schedule_results.each do |schedule_result|
      %tr
        %td= schedule_result.match_date_time ? I18n.l(schedule_result.match_date_time, format: :short) : "未定"
        %td= schedule_result.section
        %td= schedule_result.opponent
        %td
          - if schedule_result.match_result == "勝ち"
            -# TODO: スコアテーブルとリレーショナルを組み表示する
            -# 記号:○
            &#9711;
            -# (
            -# = schedule_result.section
            -# ー
            -# = schedule_result.section
            -# )
          - elsif schedule_result.match_result == "負け"
            -# 記号:×
            &#10005;
          - elsif schedule_result.match_result == "引分け"
            -# 記号:△
            &#9651;
          - else
            未定
        %td= schedule_result.stadium
        %td= schedule_result.home_and_away
        %td= I18n.l(schedule_result.created_at, format: :short)
        %td
          - if user_signed_in? && current_user.admin?
            = link_to '編集', edit_match_schedule_result_path(schedule_result.id)
            &frasl;
            = link_to '削除', match_schedule_result_path(schedule_result.id), method: :delete, data: { confirm: 'このスケジュールを削除しますか？'}
          - else
            &ndash;

app/views/match/schedule_results/new.html.haml
%dev.d-flex.align-items-center
  %h1 試合スケジュール登録

= render "form"

= form_with model: @schedule_results, url: match_schedule_results_path, local: true do |f|
  %div.form-group
    = f.label :match_date_time, '試合日時'
    = f.datetime_field :match_date_time, class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※試合日時が未定の場合、選択不要です
  %div.form-group
    = f.label :section, '節'
    = f.select :section, ScheduleResult.sections.keys, class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※第何節の試合かを選択してください
  %div.form-group
    = f.label :opponent, '対戦チーム'
    = f.select :opponent, ScheduleResult.opponents.keys, class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※対戦チームを選択してください
  %div.form-group
    = f.label :match_result, '試合結果'
    = f.select :match_result, ScheduleResult.match_results.keys, include_blank: "", class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※試合結果が未定の場合、選択不要です
  %div.form-group
    = f.label :stadium, '会場'
    = f.select :stadium, ScheduleResult.stadia.keys, class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※会場を選択してください
  %div.form-group
    = f.label :home_and_away, 'ホーム&アウェー'
    = f.select :home_and_away, ScheduleResult.home_and_aways.keys, class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※ホームまたはアウェーを選択してください

  = f.submit '登録する', class: 'btn btn-info btn-block'