config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  # schedule_results page
  resource :match do
    resources :schedule_results, controller: 'match/schedule_results', except: [:show]
  end

  # contact page
  resources :contacts, only: [:index] do
    collection do
      post :confirm
      post :thanks
    end
  end

  # players page
  resources :players, except: [:show]

  devise_for :users

  # admin page
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # 準備中 page
  get 'preparation', to: 'preparation#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/contact.rb
class Contact
  include ActiveModel::Model

  attr_accessor :contact_name, :contact_email, :contact_email_confirmation, :contact_comment

  validates :contact_name, presence: { message: '名前を入力してください' }
  validates :contact_email, presence: { message: 'メールアドレスを入力してください' }
  validates :contact_email, confirmation: { message: '確認用メールアドレスが一致しません' }
  validates :contact_email_confirmation, presence: { message: '確認用メールアドレスを入力してください' }
  validates :contact_comment, presence: { message: 'お問い合わせ内容を入力してください' }
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.new
    render :index
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.valid?
      render :confirm
    else
      render :index
    end
  end

  def thanks
    @contact = Contact.new(require_contact_params)
    ContactsMailer.received_email(@contact).deliver

    render :thanks
  end

  private
  def contact_params
    params.permit(:contact_name, :contact_email, :contact_email_confirmation, :contact_comment)
  end

  def require_contact_params
    params.require(:contact).permit(:contact_name, :contact_email, :contact_email_confirmation, :contact_comment)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.haml
= form_with model: @contact, url: thanks_contacts_path, local: true do |f|
  %dv.contact-header
    %h2 Contact 確認

  .contact-desc
    お問い合わせ内容をご確認の上、「送信する」を押してください。
    %br
    = link_to 'Contactページに戻る', contacts_path, class: 'btn'

  %table.table.contact
    %tr
      %th 名前
      %td
        = f.hidden_field :contact_name
        = @contact.contact_name
    %tr
      %th メールアドレス
      %td
        = f.hidden_field :contact_email
        = @contact.contact_email
    %trs
      %th お問い合わせ内容
      %td
        = f.hidden_field :contact_comment
        = simple_format(@contact.contact_comment)
  = f.submit '送信する', class: 'btn btn-primary'

app/views/contacts/index.html.haml
= form_with url: confirm_contacts_path, local: true do |f|
  %div.contact-header
    %h2 Contact

  - if @contact.errors.any?
    %div.alert.alert-danger
      %strong 入力内容にエラーがあるため、ご確認ください。
      %ul
        - @contact.errors.each do |attr, msg|
          %li
            = msg
  %div.contact-desc
    「メンバー募集」に関するお問い合わせ、「その他」お問い合わせはこちらのフォームよりご連絡ください。
    %br
    = link_to 'トップページに戻る', root_path, class: 'btn'

  %table.table.contact
    %tr
      %th
        名前
        %span.text-danger （必須）
      %td
        = f.text_field :contact_name
    %tr
      %th
        メールアドレス
        %span.text-danger （必須）
        %td
          = f.text_field :contact_email, placeholder: '半角英数字 （例: sproutfc@gmail.com）'
    %tr
      %th
        確認用メールアドレス
        %span.text-danger （必須）
        %td
          = f.text_field :contact_email_confirmation, placeholder: '確認のため、もう一度メールアドレスを入力してください',
                                                      oncopy: 'return false',
                                                      onpaste: 'return false',
                                                      oncontextmenu: 'return false'
    %tr
      %th お問い合わせ内容
      %td
        = f.text_area :contact_comment
  = f.submit '確認画面へ', class: 'btn btn-primary'

app/views/contacts/thanks.html.haml
%dv.contact-header
  %h2 Contact 完了

%div.contact-desc
  お問い合わせいただきありがとうございました！
  %br
  お問い合わせ内容は管理者宛にメールで送信されました。
  %br
  内容を確認の上、ご返信致しますのでしばしお待ちくださいませ。
  %br
  = link_to 'トップページに戻る', root_path, class: 'btn'