config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  # schedule_results page
  resource :match do
    resources :schedule_results, controller: 'match/schedule_results', except: [:show]
  end

  # contact page
  resources :contacts, only: [:index] do
    collection do
      post :confirm
      post :thanks
    end
  end

  # players page
  resources :players, except: [:show]

  devise_for :users

  # admin page
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # 準備中 page
  get 'preparation', to: 'preparation#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/player.rb
class Player < ApplicationRecord
  mount_uploader :image, ImageUploader

  enum position: { GK: 1, DF: 2, MF: 3, FW: 4 }

  validates :name, presence: { message: '選手名を入力してください' },
                    length: { maximum: 10, message: '選手名は10文字以下に設定して下さい' }
  validates :squad_number, presence: { message: '背番号を選択してください' },
                            uniqueness: { message: '選択した背番号は既に使用されています' }
  validates :position, presence: { message: 'ポジションを選択してください' }
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @players = Player.all.order(position: "ASC")
  end

  def new
    if admin_user?
      @players = Player.new
    else
      flash[:success] = '権限がないためアクセスできません'
      redirect_to players_path
    end
  end

  def create
    @players = Player.create(player_params)
    if @players.save
      flash[:success] = '選手登録が完了しました'
      redirect_to players_path
    else
      render :new
    end
  end

  def edit
    if admin_user?
      @players = find_player_id
    else
      flash[:success] = '権限がないためアクセスできません'
      redirect_to players_path
    end
  end

  def update
    @players = find_player_id
    if @players.update(require_player_params)
      flash[:success] = '更新が完了しました'
      redirect_to players_path
    else
      render :edit
    end

  end

  def destroy
    player = find_player_id
    player.destroy
    flash[:success] = '削除が完了しました'
    redirect_to players_path
  end

  private
  def find_player_id
    Player.find(params[:id])
  end

  def player_params
    params.permit(:name, :squad_number, :position, :image, :image_cache)
  end

  def require_player_params
    params.require(:player).permit(:name, :squad_number, :position, :image, :image_cache)
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.haml
%div.section-input_schedule
  %div.ml-auto.posts_button.post
    = link_to '選手一覧に戻る', players_path, title: '選手一覧', class: 'botton'

app/views/players/edit.html.haml
%dev.d-flex.align-items-center
  %h1 選手登録の編集

= render "form"
-#TODO: _fromパーシャルでedit/newをまとめる
= form_with model: @players, local: true do |f|

  - if @players.errors.any?
    %div.alert.alert-denger
      %stronge 入力内容にエラーがあるため、確認ください。
      %ul
        - @players.errors.each do |attr, msg|
          %li
            = msg

  %div.form-group
    = f.label :name, '選手名'
    = f.text_field :name , class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※選手名を入力してください（10文字以内）
  %div.form-group
    = f.label :squad_number, '背番号'
    = f.select :squad_number, options_for_select(0..100), include_blank: '選択してください', class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※選手の背番号を選択して下さい
  %div.form-group
    = f.label :position, 'ポシション'
    = f.select :position, Player.positions.keys, include_blank: '', class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※選手のポジションを選択して下さい
  %div.form-group
    = f.label :image, '選手写真'
    %br
    = image_tag @players.image.thumb.url if @players.image?
    = f.file_field :image
    = f.hidden_field :image_cache
    %form-text.text-muted#small.title-tip
      ※選手写真がない場合、ファイル選択は不要です。

  = f.submit '登録を更新する', class: 'btn btn-info btn-block'

app/views/players/index.html.haml
%div.players-heading
  %h2 TEAM

- if user_signed_in? && current_user.admin?
  %div.section-input_schedule
    %div.ml-auto.buttom.post
      %div.btn.btn-outline-info
        = link_to '選手を登録する', new_player_path, title: '試合日程・結果一覧', class: 'button'

%div.players-img
  = image_tag 'team.jpg'

%div.players-heading
  %h2 PLAYERS
- if @players.present?
  %div.players-container
    - @players.each do |player|
      %div.post-container
        %div.summary
          -#TODO :image_uploaderでdefault表示する
          - if player.image?
            = image_tag player.image.url
          - else
            = image_tag 'default.png', size: '225x300'
          %br
          %br
          選手名：
          = player.name
          %br
          背番号：
          = player.squad_number
          %br
          ポジション：
          = player.position
          %br
          - if user_signed_in? && current_user.admin?
            = link_to '編集', edit_player_path(player.id)
            &frasl;
            = link_to '削除', player_path(player.id), method: :delete, data: { confirm: "#{player.name}の選手登録を削除しますか？"}
- else
  %div.non-players
    %strong
      登録されている選手はおりません。

app/views/players/new.html.haml
%dev.d-flex.align-items-center
  %h1 選手登録
%div.section-input_schedule
  %div.ml-auto.posts_button.post
    = link_to '選手一覧に戻る', players_path, title: '選手一覧', class: 'botton'

= form_with url: players_path, local: true do |f|

  - if @players.errors.any?
    %div.alert.alert-denger
      %stronge 入力内容にエラーがあるため、確認ください。
      %ul
        - @players.errors.each do |attr, msg|
          %li
            = msg

  %div.form-group
    = f.label :name, '選手名'
    = f.text_field :name , class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※選手名を入力してください（10文字以内）
  %div.form-group
    = f.label :squad_number, '背番号'
    = f.select :squad_number, options_for_select(0..100), include_blank: '選択してください', class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※選手の背番号を選択して下さい
  %div.form-group
    = f.label :position, 'ポシション'
    = f.select :position, Player.positions.keys, include_blank: '', class: 'form-control'
    %form-text.text-muted#small.title-tip
      ※選手のポジションを選択して下さい
  %div.form-group
    = f.label :image, '選手写真'
    %br
    = image_tag @players.image.thumb.url if @players.image?
    = f.file_field :image
    = f.hidden_field :image_cache
    %form-text.text-muted#small.title-tip
      ※選手写真がない場合、ファイル選択は不要です。

  = f.submit '選手を登録する', class: 'btn btn-info btn-block'