config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  # schedule_results page
  resource :match do
    resources :schedule_results, controller: 'match/schedule_results', except: [:show]
  end

  # contact page
  resources :contacts, only: [:index] do
    collection do
      post :confirm
      post :thanks
    end
  end

  # players page
  resources :players, except: [:show]

  devise_for :users

  # admin page
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # 準備中 page
  get 'preparation', to: 'preparation#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    &copy;2011-
    = Time.now.year
    SPROUT FOOTBALL CLUB. All Rights Reserved.
  %nav
    %ul
      - if user_signed_in?
        %li{ style: 'font-weight: bold; border-bottom: 1px solid #CC0000;' }
          現在
          = current_user.nickname
          でログイン中
        %li
          = link_to "ログアウト", destroy_user_session_path, method: :delete
      - else
        %li
          = link_to "ログイン", new_user_session_path
        %li
          = link_to "新規アカウント登録", new_user_registration_path

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse", style="background-color: #fff; border-color: #CC0000; border-width: 0 0 5px;">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= image_tag 'logo.jpg', size: '53x50' %>
      <%= link_to "SPROUT FC", root_path, id: "logo" %>
    </div>
    <nav>
      <ul id="navbar" class="nav navbar-nav navbar-right navbar-collapse collapse">
        <li><%= link_to "試合日程・結果", match_schedule_results_path, style: 'color: #000;' %></li>
        <li><%= link_to "順位表", preparation_path, style: 'color: #000;' %></li>
        <li><%= link_to "選手紹介", players_path, style: 'color: #000;' %></li>
        <li><%= link_to "動画/写真", preparation_path, style: 'color: #000;' %></li>
        <li><%= link_to "お問い合わせ", contacts_path, style: 'color: #000;' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag     'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag     'https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.0/css/swiper.min.css' %>
<%= javascript_include_tag  'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  <head>
    <title>Sprout FC</title>
    <%= render 'layouts/rails_default'%>
    <%= render 'layouts/shim' %>
    <%= analytics_init if Rails.env.production? %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class = "container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class:"alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>